### ISSUE TITLE
odf subvolume ls fails if there are zero cephfs volumes 

### ISSUE THREAD

**Issue by netzzer** [red-hat-storage/odf-cli#21]
Issue is odf subvolume ls fails if there are zero cephfs volumes.

Versions:
OCP 4.14.6
ODF 4.15 (downstream build 112)

```
$ ./bin/odf -n openshift-storage --operator-namespace openshift-storage subvolume ls
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x21cffdf]

goroutine 1 [running]:
github.com/rook/kubectl-rook-ceph/pkg/filesystem.getK8sRefSubvolume({0x28454f0, 0x3520420}, 0x0?)
	/Users/aclewett/go/pkg/mod/github.com/rook/kubectl-rook-ceph@v0.6.1-0.20231211183203-70ede2704719/pkg/filesystem/subvolume.go:55 +0x17f
github.com/rook/kubectl-rook-ceph/pkg/filesystem.List({0x28454f0, 0x3520420}, 0x5?, {0x7ff7bfeffa9c, 0x11}, {0x7ff7bfeffa75, 0x11}, 0x0?)
	/Users/aclewett/go/pkg/mod/github.com/rook/kubectl-rook-ceph@v0.6.1-0.20231211183203-70ede2704719/pkg/filesystem/subvolume.go:43 +0x4b
github.com/red-hat-storage/odf-cli/cmd/odf/subvolume.glob..func1(0xc000410100?, {0x25d729b?, 0x4?, 0x25d728b?})
	/Users/aclewett/ocp4.15/odf-cli/cmd/odf/subvolume/subvolume.go:21 +0xa5
github.com/spf13/cobra.(*Command).execute(0x34dcf00, {0xc0000400d0, 0x0, 0x0})
	/Users/aclewett/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0x34dbdc0)
	/Users/aclewett/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/aclewett/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	/Users/aclewett/ocp4.15/odf-cli/cmd/odf/main.go:14 +0x74
```

**Comment by yati1998** [comment]
Thanks @Madhu-1 for checking it out, I will take care of it.

**Comment by subhamkrai** [comment]
@yati1998 This first need to be fixed on the upstream side, JFYI

**Comment by yati1998** [comment]
https://github.com/red-hat-storage/odf-cli/pull/22

**Comment by yati1998** [comment]
@netzzer we can now close this issue, it is being resolved.
